name: NetflixMovieCatalog Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |                 
          if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
            echo "Your DockerHub username and password should be set as secrets!"
            exit 1
          fi
          
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
          IMAGE_NAME=$DOCKER_USERNAME/netflix-movie-catalog:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
