name: NetflixFrontend stack build-deploy

on:
  push:
    branches:
     - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Buid and push docker images
        run: |
           # TODO build docker image

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: YOUR_NETFLIX_INFRA_REPO  # TODO change me
          token: ${{ secrets.REPO_TOKEN }}  # The GITHUB_TOKEN secret is a GitHub access token.
          path: ./NetflixInfra

      - name: Update YAML manifests
        run: |
           cd ./NetflixInfra
           # TODO commit & push changes to infra repo
           

      - name: Commit and Push changes
        run: |
           cd ./NetflixInfra
           # TODO commit & push changes to infra repo